<HomeScreen>:
    BoxLayout:
        orientation: 'vertical'
        MDRaisedButton:
            text: "Host Match"
            on_release:
                root.manager.current = 'create_game_screen'
        MDRaisedButton:
            text: "Join Match"
            on_release:
                root.manager.current = 'lobby_browser_screen'
        MDRaisedButton:
            text: "Local Game"
            on_release:
                root.start_local_game()

